### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by zaicopx** [AnchyDev/ReusablePotion#1]
Im using this repo: https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots
and I got this error

> 18>modules.lib(ReusablePotion.obj) : error LNK2001: unresolved external symbol "public: virtual void __cdecl ReusablePotionPlayerScript::OnPlayerEnterCombat(class Player *,class Unit *)" (?OnPlayerEnterCombat@ReusablePotionPlayerScript@@UEAAXPEAVPlayer@@PEAVUnit@@@Z)
18>G:\Compile Server\Projects\zaicopx-AzerothCore\AzerothCore\Build\bin\Release\worldserver.exe : fatal error LNK1120: 1 unresolved externals
18>Done building project "worldserver.vcxproj" -- FAILED.

**Comment by AnchyDev** [comment]
Have you updated to the most recent version?

**Comment by zaicopx** [comment]
Ahh I seem to have forgotten to git pull. 
Thank you, everything went smoothly
